version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: weolbu-cyj-redis-container
    ports:
      - "6379:6379"
    volumes:
      - weolbu-cyj-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  weolbu-cyj-redis-data:
