server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 1800000          # Access Token ?? ?? 30?
    refresh-token-expiration: 1209600000      # Refresh Token ?? ?? 14?
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      password:
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
